/// Flutter icons Hamd
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Hamd
///      fonts:
///       - asset: fonts/Hamd.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Hamd {
  Hamd._();

  static const _kFontFam = 'Hamd';
  static const String _kFontPkg = null;

  static const IconData star_rate = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_rate_active = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
